@s:\tc20\tcc -c -ml -O -Z -N rfrun1 rfrun2 rfintf mo xar xvv xcf xjak xvv5 xgcd
@h:\ref\refal xcv (ns)
@rem refal xgcd (ns)
@tlib h:\ref\reflib +rfrun1 +rfrun2 +rfintf +mo +xar +xvv +xcf +xjak +xcv +xgcd +xvv5, reflib.cat
@erase rfrun1.obj
@erase rfrun2.obj
@erase rfintf.obj
@erase mo.obj
@erase xar.obj
@erase xvv.obj
@erase xcv.obj
@erase xcf.obj
@erase xjak.obj
@erase xgcd.obj
@erase xvv5.obj